name: demo workflow
on: schedule
  - cron: '45 2 * * *'
    timezone: Asia/Kolkata
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "Hellooo, I am Banu"

      