name: demo workflow
on: 
  schedule:
    - cron: '20 9 * * *'
  
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello message
        run: echo "Hellooo, I am Banu"

      